# -*- coding: utf-8 -*-
"""ENSC429_SRProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qSlH_NTTungEXVDzqkuB65iXzmnZF3SV
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/SR_ENSC429_Project/data
!python download_div2k.py --out_dir ./DIV2K --subset both

!pip install lpips scikit-image -q
from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/SR_ENSC429_Project/data
from dataset import DIV2KDataset

train_ds = DIV2KDataset('./DIV2K/DIV2K_train_HR', scale=4, patch_size=96, train=True)
print(len(train_ds))
lr, hr = train_ds[0]
print(lr.shape, hr.shape)

import matplotlib.pyplot as plt
import numpy as np

eval_ds = DIV2KDataset('./DIV2K/DIV2K_valid_HR', scale=4, patch_size=96, train=False)
lr, hr = eval_ds[0]

# convert CHW tensor -> HWC numpy for display, and BGR -> RGB since cv2 loads as BGR
lr_img = lr.permute(1, 2, 0).numpy()[:, :, ::-1]
hr_img = hr.permute(1, 2, 0).numpy()[:, :, ::-1]

fig, axes = plt.subplots(1, 2, figsize=(10, 5))
axes[0].imshow(lr_img); axes[0].set_title(f"LR {tuple(lr.shape)}")
axes[1].imshow(hr_img); axes[1].set_title(f"HR {tuple(hr.shape)}")
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/SR_ENSC429_Project
!pip install scikit-image lpips -q
!python baselines.py --hr_dir ./data/DIV2K/DIV2K_valid_HR --out_dir ./results

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/SR_ENSC429_Project
!python train_srcnn.py --hr_dir ./data/DIV2K/DIV2K_train_HR --out_dir ./results --epochs 20 --batch_size 16

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/SR_ENSC429_Project
!python evaluate_esrgan.py --hr_dir ./data/DIV2K/DIV2K_valid_HR --checkpoint ./models/RealESRGAN_x4plus.pth --out_dir ./results

!python evaluate_srcnn.py --hr_dir ./data/DIV2K/DIV2K_valid_HR --checkpoint ./results/srcnn_final.pth --out_dir ./results